trigger: none # Disable push triggers

pr:
- dev

resources:
  repositories:
    - repository: 1P
      type: git
      name: IDDP/msal-javascript-1p
      ref: central-pipelines

jobs:
  - template: .pipelines/templates/build-test.yml@1P
    parameters:
      branch: $(System.PullRequest.SourceBranch)
      lib-name: msal-browser
