trigger: none # Disable push triggers

pr:
- dev

resources:
  repositories:
    - repository: 1P
      type: git
      name: IDDP/msal-javascript-1p
      ref: master

jobs:
  - template: Build-Test.yml@1P
